fba_locations = {'*XFR': {'address': '2021 7th Avenue',
  'city': 'Seattle',
  'code': '*XFR',
  'notes': '',
  'state': 'WA',
  'zip': '98121'},
 'ABE1': {'address': '705 Boulder Dr',
  'city': 'Breinigsville',
  'code': 'ABE1',
  'notes': '',
  'state': 'PA',
  'zip': '18105'},
 'ABE2': {'address': '705 Boulder Drive',
  'city': 'Breinigsville',
  'code': 'ABE2',
  'notes': '600000',
  'state': 'PA',
  'zip': '18031'},
 'ABE3': {'address': '650 Boulder Drive',
  'city': 'Breinigsville',
  'code': 'ABE3',
  'notes': '997400',
  'state': 'PA',
  'zip': '18031'},
 'ABE4': {'address': '1610 Van Buren Road',
  'city': 'Easton',
  'code': 'ABE4',
  'notes': '1106400',
  'state': 'PA',
  'zip': '18045'},
 'ABE5': {'address': '100 Quality Circle Suite 107',
  'city': 'Harrisburg',
  'code': 'ABE5',
  'notes': '200000',
  'state': 'PA',
  'zip': '17112'},
 'ABE7': {'address': '12510 Micro Dr',
  'city': 'Mira Loma',
  'code': 'ABE7',
  'notes': '',
  'state': 'CA',
  'zip': '91752'},
 'ABE8': {'address': '401 Independence Road',
  'city': 'Florence',
  'code': 'ABE8',
  'notes': '613000',
  'state': 'NJ',
  'zip': '8518'},
 'ABEX': {'address': '698 Route 46 West',
  'city': 'Teterboro',
  'code': 'ABEX',
  'notes': '617000',
  'state': 'NJ',
  'zip': '7608'},
 'ACY1': {'address': '240 Mantua Grove Rd',
  'city': 'West Deptford',
  'code': 'ACY1',
  'notes': '',
  'state': 'NJ',
  'zip': '8066'},
 'ACY5': {'address': '2277 Center Square Rd',
  'city': 'Swedesboro, Logan Township',
  'code': 'ACY5',
  'notes': '202900',
  'state': 'NJ',
  'zip': '8085'},
 'ALT9': {'address': '(920 Highway 124)',
  'city': 'Braselton',
  'code': 'ALT9',
  'notes': '600000',
  'state': 'GA',
  'zip': '30517'},
 'ATL6': {'address': '4200 North Commerce Dr.',
  'city': 'East Point',
  'code': 'ATL6',
  'notes': '301200',
  'state': 'GA',
  'zip': '30344'},
 'ATL7': {'address': '6855 Shannon Pkwy',
  'city': 'Union City',
  'code': 'ATL7',
  'notes': '517100',
  'state': 'GA',
  'zip': '30291'},
 'ATL8': {'address': '2201 Thorton Road',
  'city': 'Lithia Springs',
  'code': 'ATL8',
  'notes': '733200',
  'state': 'GA',
  'zip': '30122'},
 'ATL9': {'address': '2232 Northmont Parkway',
  'city': 'Duluth',
  'code': 'ATL9',
  'notes': '',
  'state': 'GA',
  'zip': '30096'},
 'AVP1': {'address': '550 Oak Ridge Road',
  'city': 'Hazleton',
  'code': 'AVP1',
  'notes': '630000',
  'state': 'PA',
  'zip': '18202'},
 'AVP2': {'address': '298 1st Ave',
  'city': 'Gouldsboro',
  'code': 'AVP2',
  'notes': '500000',
  'state': 'PA',
  'zip': '18424'},
 'AVP3': {'address': '289 1st Ave, Gouldsboro pa',
  'city': 'Wayne',
  'code': 'AVP3',
  'notes': '1250000',
  'state': 'PA',
  'zip': '18424'},
 'AVP6': {'address': '1 Commerce Rd',
  'city': 'Pittston',
  'code': 'AVP6',
  'notes': '437440',
  'state': 'PA',
  'zip': '18640'},
 'AVP8': {'address': '250 Enterprise Way',
  'city': 'Pittston',
  'code': 'AVP8',
  'notes': '399500',
  'state': 'PA',
  'zip': '18640'},
 'BDL1': {'address': '200 Old Iron Ore Rd',
  'city': 'Windsor',
  'code': 'BDL1',
  'notes': '1017500',
  'state': 'CT',
  'zip': '6095'},
 'BDL2': {'address': '409 Washington Ave',
  'city': 'North Haven',
  'code': 'BDL2',
  'notes': '',
  'state': 'CT',
  'zip': '6473'},
 'BDL5': {'address': '29 Research Parkway',
  'city': 'Wallingford',
  'code': 'BDL5',
  'notes': '184100',
  'state': 'CT',
  'zip': '6492'},
 'BFI1': {'address': '1800 140th Avenue Suite A',
  'city': 'Sumner',
  'code': 'BFI1',
  'notes': '492000',
  'state': 'WA',
  'zip': '98390'},
 'BFI3': {'address': '2700 Center Drive',
  'city': 'DuPont',
  'code': 'BFI3',
  'notes': '1000000',
  'state': 'WA',
  'zip': '98327'},
 'BFI4': {'address': '21005 64th Ave S',
  'city': 'Kent',
  'code': 'BFI4',
  'notes': '1000000',
  'state': 'WA',
  'zip': '98032'},
 'BFI5': {'address': '20529 59th Place South, Building B',
  'city': 'Kent',
  'code': 'BFI5',
  'notes': '318200',
  'state': 'WA',
  'zip': '98032'},
 'BFI6': {'address': '20202 84th Avenue South',
  'city': 'Kent',
  'code': 'BFI6',
  'notes': '',
  'state': 'WA',
  'zip': '98032'},
 'BFI7': {'address': '1901 140th Ave E',
  'city': 'Sumner',
  'code': 'BFI7',
  'notes': '',
  'state': 'WA',
  'zip': '98390'},
 'BFIX': {'address': '1800 140th Avenue Suite XB',
  'city': 'Sumner',
  'code': 'BFIX',
  'notes': '',
  'state': 'WA',
  'zip': '98390'},
 'BNA1': {'address': '14840 Central Pike Suite 190',
  'city': 'Lebanon',
  'code': 'BNA1',
  'notes': '449000',
  'state': 'TN',
  'zip': '37090'},
 'BNA2': {'address': '500 Duke Dr',
  'city': 'Lebanon',
  'code': 'BNA2',
  'notes': '1200000',
  'state': 'TN',
  'zip': '37090'},
 'BNA3': {'address': '2020 Joe B Jackson Pkwy',
  'city': 'Murfreesboro',
  'code': 'BNA3',
  'notes': '1000000',
  'state': 'TN',
  'zip': '37127'},
 'BNA4': {'address': '50 Airways Blvd.',
  'city': 'Nashville',
  'code': 'BNA4',
  'notes': '',
  'state': 'TN',
  'zip': '37217'},
 'BNA5': {'address': '50 Airways Blvd.',
  'city': 'Nashville',
  'code': 'BNA5',
  'notes': '214000',
  'state': 'TN',
  'zip': '37217'},
 'BOS1': {'address': '10 State St',
  'city': 'Nashua',
  'code': 'BOS1',
  'notes': '63750',
  'state': 'NH',
  'zip': '3063'},
 'BOS3': {'address': '',
  'city': 'Fall River',
  'code': 'BOS3',
  'notes': '',
  'state': 'MA',
  'zip': '2720'},
 'BOS5': {'address': '1000 Technology Center Drive',
  'city': 'Stoughton',
  'code': 'BOS5',
  'notes': '332700',
  'state': 'MA',
  'zip': '2072'},
 'BOS6': {'address': '201 Beachman St',
  'city': 'Everett',
  'code': 'BOS6',
  'notes': '96600',
  'state': 'MA',
  'zip': '2149'},
 'BOS7': {'address': '1180 Innovation Way',
  'city': 'Fall River',
  'code': 'BOS7',
  'notes': '1000000',
  'state': 'MA',
  'zip': '2722'},
 'BUF5': {'address': '4201 Walden Ave',
  'city': 'Lancaster',
  'code': 'BUF5',
  'notes': '',
  'state': 'NY',
  'zip': '14086'},
 'BWI0': {'address': '2010 Broening Highway',
  'city': 'Baltimore',
  'code': 'BWI0',
  'notes': '1017550',
  'state': 'MD',
  'zip': '21224'},
 'BWI1': {'address': '45121 Global Plaza',
  'city': 'Sterling',
  'code': 'BWI1',
  'notes': '80900',
  'state': 'VA',
  'zip': '20166'},
 'BWI2': {'address': '2010 Broening Hwy.',
  'city': 'Baltimore',
  'code': 'BWI2',
  'notes': '',
  'state': 'MD',
  'zip': '21224'},
 'BWI4': {'address': '165 Business Blvd',
  'city': 'Clear Brook',
  'code': 'BWI4',
  'notes': '',
  'state': 'VA',
  'zip': '22624'},
 'BWI5': {'address': '5001 Holabird Ave.',
  'city': 'Baltimore',
  'code': 'BWI5',
  'notes': '345000',
  'state': 'MD',
  'zip': '21224'},
 'BWI6': {'address': '5617 Industrial Drive',
  'city': 'Springfield',
  'code': 'BWI6',
  'notes': '127300',
  'state': 'VA',
  'zip': '22151'},
 'CAE1': {'address': '4400 12 Street Extension',
  'city': 'West Columbia',
  'code': 'CAE1',
  'notes': '1250000',
  'state': 'SC',
  'zip': '29172'},
 'CAE3': {'address': '222 Old Wire Road',
  'city': 'West Columbia',
  'code': 'CAE3',
  'notes': '',
  'state': 'SC',
  'zip': '29172'},
 'CHA1': {'address': '7200 Discovery Drive',
  'city': 'Chattanooga',
  'code': 'CHA1',
  'notes': '1020000',
  'state': 'TN',
  'zip': '37416'},
 'CHA2': {'address': '225 Infinity Dr NW',
  'city': 'Charleston',
  'code': 'CHA2',
  'notes': '1200000',
  'state': 'TN',
  'zip': '37310'},
 'CHS1': {'address': '7290 Investment Drive',
  'city': 'N Charleston',
  'code': 'CHS1',
  'notes': '128200',
  'state': 'SC',
  'zip': '29418'},
 'CLE2': {'address': '21500 Emery Rd',
  'city': 'North Randall',
  'code': 'CLE2',
  'notes': '',
  'state': 'OH',
  'zip': '44128'},
 'CLE5': {'address': '8685 Independence Parkway',
  'city': 'Twinsburg',
  'code': 'CLE5',
  'notes': '248000',
  'state': 'OH',
  'zip': '44087'},
 'CLT1': {'address': '7035 Northwinds Drive',
  'city': 'Concord',
  'code': 'CLT1',
  'notes': '',
  'state': 'NC',
  'zip': '28027'},
 'CLT2': {'address': '10240 Old Dowd Road',
  'city': 'Charlotte',
  'code': 'CLT2',
  'notes': '397800',
  'state': 'NC',
  'zip': '28214'},
 'CLT3': {'address': '6500 Davidson Hwy',
  'city': 'Concord',
  'code': 'CLT3',
  'notes': '',
  'state': 'NC',
  'zip': '28027'},
 'CLT5': {'address': '1745 Derita Rd.',
  'city': 'Concord',
  'code': 'CLT5',
  'notes': '222500',
  'state': 'NC',
  'zip': '28027'},
 'CMH0': {'address': '11903 National RD SW Etna Township Park',
  'city': 'Etna',
  'code': 'CMH0',
  'notes': '800000',
  'state': 'OH',
  'zip': '43062'},
 'CMH1': {'address': '11903 National Road SW',
  'city': 'Etna',
  'code': 'CMH1',
  'notes': '855000',
  'state': 'OH',
  'zip': '43062'},
 'CMH2': {'address': '6050 Gateway Court',
  'city': 'Groveport',
  'code': 'CMH2',
  'notes': '1000000',
  'state': 'OH',
  'zip': '43125'},
 'CMH3': {'address': '700 GATEWAY BLVD',
  'city': 'MONROE',
  'code': 'CMH3',
  'notes': '',
  'state': 'OH',
  'zip': '45050'},
 'CODE': {'address': 'Address',
  'city': 'City',
  'code': 'CODE',
  'notes': 'Size',
  'state': 'State',
  'zip': 'Zip Code'},
 'CVG1': {'address': '1155 Worldwide Blvd.',
  'city': 'Hebron',
  'code': 'CVG1',
  'notes': '484000',
  'state': 'KY',
  'zip': '41048'},
 'CVG2': {'address': '1600 Worldwide Blvd.',
  'city': 'Hebron',
  'code': 'CVG2',
  'notes': '543000',
  'state': 'KY',
  'zip': '41048'},
 'CVG3': {'address': '3680 Langley Dr.',
  'city': 'Hebron',
  'code': 'CVG3',
  'notes': '711400',
  'state': 'KY',
  'zip': '41048'},
 'CVG5': {'address': '2285 Litton Way',
  'city': 'Hebron',
  'code': 'CVG5',
  'notes': '598000',
  'state': 'KY',
  'zip': '41048'},
 'CVG7': {'address': '2285 Litton Lane',
  'city': 'Hebron',
  'code': 'CVG7',
  'notes': '',
  'state': 'KY',
  'zip': '41048'},
 'CVG8': {'address': '7968 Kentucky Drive Suites 2-3',
  'city': 'Florence',
  'code': 'CVG8',
  'notes': '',
  'state': 'KY',
  'zip': '41042'},
 'CVG9': {'address': '2305 Litton Lane',
  'city': 'Hebron',
  'code': 'CVG9',
  'notes': '',
  'state': 'KY',
  'zip': '41048'},
 'DAL6': {'address': '4601 Gold Spike Drive',
  'city': 'Fort Worth',
  'code': 'DAL6',
  'notes': '',
  'state': 'TX',
  'zip': '76106'},
 'DAL9': {'address': '1400 SOUTHPORT PKWY',
  'city': 'WILMER',
  'code': 'DAL9',
  'notes': '',
  'state': 'TX',
  'zip': '75172'},
 'DAU1': {'address': '2093-2209 Rutland Dr',
  'city': 'Austin',
  'code': 'DAU1',
  'notes': '',
  'state': 'TX',
  'zip': '78758'},
 'DAV1': {'address': '1 Shields Ave, Room 182',
  'city': 'Davis',
  'code': 'DAV1',
  'notes': '',
  'state': 'CA',
  'zip': '95616'},
 'DAY3': {'address': '700 Gateway Blvd',
  'city': 'Monroe',
  'code': 'DAY3',
  'notes': '1000000',
  'state': 'OH',
  'zip': '45050'},
 'DB01': {'address': '201 Beacham Street',
  'city': 'Everett (Chelsea)',
  'code': 'DB01',
  'notes': '96600',
  'state': 'MA',
  'zip': '2149'},
 'DB02': {'address': '500 Sprague St.',
  'city': 'Dedham',
  'code': 'DB02',
  'notes': '60500',
  'state': 'MA',
  'zip': '2026'},
 'DCA1': {'address': '1700 SPARROWS POINT BLVD.',
  'city': 'SPARROWS POINT',
  'code': 'DCA1',
  'notes': '',
  'state': 'MD',
  'zip': '21219'},
 'DCH1': {'address': '2801 S. Western Ave.',
  'city': 'Chicago',
  'code': 'DCH1',
  'notes': '150000',
  'state': 'IL',
  'zip': '60608'},
 'DCH2': {'address': '8220 Austin Ave.',
  'city': 'Morton Grove',
  'code': 'DCH2',
  'notes': '39300',
  'state': 'IL',
  'zip': '60053'},
 'DCH3': {'address': '4500 Western Ave.',
  'city': 'Lisle',
  'code': 'DCH3',
  'notes': '68000',
  'state': 'IL',
  'zip': '60532'},
 'DDC1': {'address': '12401 North Stemmons Fwy.',
  'city': 'Farmers Branch',
  'code': 'DDC1',
  'notes': '183000',
  'state': 'TX',
  'zip': '75234'},
 'DDC2': {'address': '861 E Gude Drive',
  'city': 'Rockville',
  'code': 'DDC2',
  'notes': '65000',
  'state': 'MD',
  'zip': '20850'},
 'DEN1': {'address': '189 W 144th Ave',
  'city': 'Thornton',
  'code': 'DEN1',
  'notes': '855000',
  'state': 'CO',
  'zip': '80023'},
 'DEN2': {'address': '24006 East 19th Ave',
  'city': 'Aurora',
  'code': 'DEN2',
  'notes': '',
  'state': 'CO',
  'zip': '80019'},
 'DEN3': {'address': '14601 Grant Street',
  'city': 'Thornton',
  'code': 'DEN3',
  'notes': '',
  'state': 'CO',
  'zip': '80023'},
 'DEN5': {'address': '19799 E. 36th Avenue. Majestic Commercenter Building #29',
  'city': 'Aurora',
  'code': 'DEN5',
  'notes': '452400',
  'state': 'CO',
  'zip': '80011'},
 'DEN6': {'address': '480 E 55th Ave',
  'city': 'Denver',
  'code': 'DEN6',
  'notes': '',
  'state': 'CO',
  'zip': '80216'},
 'DET1': {'address': '38171 Amrhein Rd',
  'city': 'Livonia',
  'code': 'DET1',
  'notes': '',
  'state': 'MI',
  'zip': '48150'},
 'DET2': {'address': '50500 Mound Rd',
  'city': 'Shelby Township',
  'code': 'DET2',
  'notes': '',
  'state': 'MI',
  'zip': '48317'},
 'DEW1': {'address': '2 Empire Boulevard',
  'city': 'Moonachie',
  'code': 'DEW1',
  'notes': '75000',
  'state': 'NJ',
  'zip': '7074'},
 'DFW1': {'address': '2700 Regent Blvd',
  'city': 'DFW Airport',
  'code': 'DFW1',
  'notes': '',
  'state': 'TX',
  'zip': '75261'},
 'DFW6': {'address': '940 W Bethel Road',
  'city': 'Coppell',
  'code': 'DFW6',
  'notes': '1000000',
  'state': 'TX',
  'zip': '75019'},
 'DFW7': {'address': '700 Westport Parkway',
  'city': 'Fort Worth',
  'code': 'DFW7',
  'notes': '1100000',
  'state': 'TX',
  'zip': '76177'},
 'DFW8': {'address': '2700 Regent Blvd.',
  'city': 'Irving',
  'code': 'DFW8',
  'notes': '428500',
  'state': 'TX',
  'zip': '75063'},
 'DFW9': {'address': '2700 Regent Blvd',
  'city': 'Irving',
  'code': 'DFW9',
  'notes': '',
  'state': 'TX',
  'zip': '75063'},
 'DJA1': {'address': '11084 Cabot Commerce Circle',
  'city': 'Jacksonville',
  'code': 'DJA1',
  'notes': '63000',
  'state': 'FL',
  'zip': '32226'},
 'DLA1': {'address': '900 W Florence Ave.',
  'city': 'Inglewood',
  'code': 'DLA1',
  'notes': '27740',
  'state': 'CA',
  'zip': '90301'},
 'DLA2': {'address': '5650 Dolly Ave.',
  'city': 'Buena Park',
  'code': 'DLA2',
  'notes': '330000',
  'state': 'CA',
  'zip': '90621'},
 'DLA3': {'address': '5829 Smithway St.',
  'city': 'Commerce',
  'code': 'DLA3',
  'notes': '48400',
  'state': 'CA',
  'zip': '90040'},
 'DLA4': {'address': '9031 Lurline Ave.',
  'city': 'Chatsworth',
  'code': 'DLA4',
  'notes': '29200',
  'state': 'CA',
  'zip': '91311'},
 'DLA5': {'address': '6250 Sycamore Canyon Blvd.',
  'city': 'Riverside',
  'code': 'DLA5',
  'notes': '36000',
  'state': 'CA',
  'zip': '92507'},
 'DLA8': {'address': '2815 W. El Segundo Blvd.',
  'city': 'Hawthorne',
  'code': 'DLA8',
  'notes': '170000',
  'state': 'CA',
  'zip': '90250'},
 'DM01': {'address': 'Tangelo Park',
  'city': 'Orlando',
  'code': 'DM01',
  'notes': '',
  'state': 'FL',
  'zip': '32189'},
 'DM11': {'address': '15600 NW 15th Ave.',
  'city': 'Miami Gardens',
  'code': 'DM11',
  'notes': '37400',
  'state': 'FL',
  'zip': '33169'},
 'DMI2': {'address': '3200 Northwest 67th Avenue',
  'city': 'Miami',
  'code': 'DMI2',
  'notes': '117200',
  'state': 'FL',
  'zip': '33122'},
 'DML1': {'address': '3935 W. Mitchell St.',
  'city': 'Milwaukee',
  'code': 'DML1',
  'notes': '50000',
  'state': 'WI',
  'zip': '53125'},
 'DMN1': {'address': '2811 Beverly Drive',
  'city': 'Eagen',
  'code': 'DMN1',
  'notes': '142000',
  'state': 'MN',
  'zip': '55121'},
 'DP01': {'address': '',
  'city': 'Portland',
  'code': 'DP01',
  'notes': '',
  'state': 'OR',
  'zip': '75234'},
 'DPH1': {'address': '4219 Richmond Street',
  'city': 'Philadelphia',
  'code': 'DPH1',
  'notes': '65500',
  'state': 'PA',
  'zip': '19137'},
 'DPX1': {'address': '500 S. 48th Street',
  'city': 'Phoenix',
  'code': 'DPX1',
  'notes': '62900',
  'state': 'AZ',
  'zip': '85034'},
 'DSD1': {'address': '7130 Miramar Rd. 300A',
  'city': 'San Diego',
  'code': 'DSD1',
  'notes': '58400',
  'state': 'CA',
  'zip': '92121'},
 'DSD2': {'address': '2777 Loker Ave W.',
  'city': 'Carlsbad',
  'code': 'DSD2',
  'notes': '39700',
  'state': 'CA',
  'zip': '92010'},
 'DSE2': {'address': '6705 E Marginal Way',
  'city': 'Seattle',
  'code': 'DSE2',
  'notes': '26200',
  'state': 'WA',
  'zip': '98108'},
 'DSF1': {'address': '990 Beecher St.',
  'city': 'San Leandro',
  'code': 'DSF1',
  'notes': '42400',
  'state': 'CA',
  'zip': '94577'},
 'DSF3': {'address': '1700 Montague Expy.',
  'city': 'San Jose',
  'code': 'DSF3',
  'notes': '25800',
  'state': 'CA',
  'zip': '95131'},
 'DSF5': {'address': '250 Utah Avenue',
  'city': 'South San Francisco',
  'code': 'DSF5',
  'notes': '188000',
  'state': 'CA',
  'zip': '94080'},
 'DSF6': {'address': '6015 Giant Road',
  'city': 'Richmond',
  'code': 'DSF6',
  'notes': '224200',
  'state': 'CA',
  'zip': '94080'},
 'DTW1': {'address': '39000 Amrhein Rd',
  'city': 'Livonia',
  'code': 'DTW1',
  'notes': '1000000',
  'state': 'MI',
  'zip': '48150'},
 'DTW3': {'address': '23 mile and mound roads',
  'city': 'Shelby',
  'code': 'DTW3',
  'notes': '1000000',
  'state': 'MI',
  'zip': '48316'},
 'DTW5': {'address': 'Brownstown Business Center South, Building 9, 19991 Brownstown Center Dr',
  'city': 'Trenton',
  'code': 'DTW5',
  'notes': '210000',
  'state': 'MI',
  'zip': '48183'},
 'DWF9': {'address': '2700 Regent Blvd.',
  'city': 'Irving',
  'code': 'DWF9',
  'notes': '',
  'state': 'TX',
  'zip': '75063'},
 'EWR1': {'address': '50 New Canton Way',
  'city': 'Robinsville',
  'code': 'EWR1',
  'notes': '1200000',
  'state': 'NJ',
  'zip': '8691'},
 'EWR4': {'address': '50 New Canton Way',
  'city': 'Robbinsville',
  'code': 'EWR4',
  'notes': '1200000',
  'state': 'NJ',
  'zip': '8691'},
 'EWR5': {'address': '301 Blair Road #100',
  'city': 'Woodbridge (Avenel)',
  'code': 'EWR5',
  'notes': '562200',
  'state': 'NJ',
  'zip': '7001'},
 'EWR6': {'address': '275 Omar Avenue',
  'city': 'Avenel',
  'code': 'EWR6',
  'notes': '391700',
  'state': 'NJ',
  'zip': '7001'},
 'EWR7': {'address': '275 Omar Avenue',
  'city': 'Avenel',
  'code': 'EWR7',
  'notes': '',
  'state': 'NJ',
  'zip': '7011'},
 'EWR8': {'address': '8003 Industrial Ave. Building A',
  'city': 'Carteret',
  'code': 'EWR8',
  'notes': '10645',
  'state': 'NJ',
  'zip': '7008'},
 'EWR9': {'address': '8003 Industrial Parkway',
  'city': 'Carteret, Middlesex',
  'code': 'EWR9',
  'notes': '',
  'state': 'NJ',
  'zip': '7008'},
 'FAT1': {'address': '3575 S Orange Ave',
  'city': 'Fresno',
  'code': 'FAT1',
  'notes': '',
  'state': 'CA',
  'zip': '93725'},
 'FSE2': {'address': '5100 15th Ave NW',
  'city': 'Seattle',
  'code': 'FSE2',
  'notes': '',
  'state': 'WA',
  'zip': '98107'},
 'FSE3': {'address': '76 South Lander Street',
  'city': 'Seattle',
  'code': 'FSE3',
  'notes': '',
  'state': 'WA',
  'zip': '98134'},
 'FTW1': {'address': '33333 LBJ Freeway',
  'city': 'Dallas',
  'code': 'FTW1',
  'notes': '500000',
  'state': 'TX',
  'zip': '75241'},
 'FTW2': {'address': '2701 Bethel Road',
  'city': 'DeSoto',
  'code': 'FTW2',
  'notes': '1000000',
  'state': 'TX',
  'zip': '75261'},
 'FTW3': {'address': '15201 Heritage Pkwy',
  'city': 'Fort Worth',
  'code': 'FTW3',
  'notes': '1000000',
  'state': 'TX',
  'zip': '76177'},
 'FTW4': {'address': '4601 Gold Spike Drive',
  'city': 'Fort Worth',
  'code': 'FTW4',
  'notes': '318500',
  'state': 'TX',
  'zip': '76106'},
 'FTW6': {'address': '2601 W. Bethel Road',
  'city': 'DFW Airport',
  'code': 'FTW6',
  'notes': '',
  'state': 'TX',
  'zip': '76051'},
 'FTW7': {'address': '944 West Sandy Lake Rd',
  'city': 'Coppell',
  'code': 'FTW7',
  'notes': '',
  'state': 'TX',
  'zip': '75019'},
 'FTW8': {'address': '3351 Balmorhea Dr',
  'city': 'Dallas',
  'code': 'FTW8',
  'notes': '',
  'state': 'TX',
  'zip': '75241'},
 'GSP1': {'address': '402 John Dodd Rd',
  'city': 'Spartanburg',
  'code': 'GSP1',
  'notes': '1016100',
  'state': 'SC',
  'zip': '29303'},
 'HCA3': {'address': '3334 N SAN FERNANDO RD BLDG E',
  'city': 'Los Angeles',
  'code': 'HCA3',
  'notes': '',
  'state': 'CA',
  'zip': '90065'},
 'HIL1': {'address': '1111 Cherry Street',
  'city': 'Chicago',
  'code': 'HIL1',
  'notes': '',
  'state': 'IL',
  'zip': '60642'},
 'HIL2': {'address': '1111 N Cherry Ave',
  'city': 'Chicago',
  'code': 'HIL2',
  'notes': '',
  'state': 'IL',
  'zip': '60642'},
 'HOU1': {'address': '8120 Humble Westfield Rd.',
  'city': 'Humble',
  'code': 'HOU1',
  'notes': '240000',
  'state': 'TX',
  'zip': '77338'},
 'HOU2': {'address': 'Interstate 45 North and Beltway 8',
  'city': 'Houston',
  'code': 'HOU2',
  'notes': '855000',
  'state': 'TX',
  'zip': '77038'},
 'HOU3': {'address': '31555 Highway 90 E',
  'city': 'Brookshire',
  'code': 'HOU3',
  'notes': '',
  'state': 'TX',
  'zip': '77423'},
 'HOUX': {'address': '2701 W Bethel Road',
  'city': 'Coppell',
  'code': 'HOUX',
  'notes': '1000000',
  'state': 'TX',
  'zip': '75261'},
 'HTX1': {'address': '4221 Way Out West Drive',
  'city': 'Houston',
  'code': 'HTX1',
  'notes': '',
  'state': 'TX',
  'zip': '77092'},
 'HTX2': {'address': '4221 Way Out West Drive',
  'city': 'Houston',
  'code': 'HTX2',
  'notes': '',
  'state': 'TX',
  'zip': '77092'},
 'HWA1': {'address': '11710 118th Ave NE, Building B',
  'city': 'Kirkland',
  'code': 'HWA1',
  'notes': '',
  'state': 'WA',
  'zip': '98034'},
 'HWA2': {'address': '11710 118th Ave NE, Building B',
  'city': 'Kirkland',
  'code': 'HWA2',
  'notes': '',
  'state': 'WA',
  'zip': '98034'},
 'IND1': {'address': '4255 Anson Blvd',
  'city': 'Whitestown',
  'code': 'IND1',
  'notes': '1000000',
  'state': 'IN',
  'zip': '46075'},
 'IND2': {'address': '715 Airtech Pkwy',
  'city': 'Plainfield',
  'code': 'IND2',
  'notes': '947300',
  'state': 'IN',
  'zip': '46168'},
 'IND3': {'address': '717 Airtech Pkwy',
  'city': 'Plainfield',
  'code': 'IND3',
  'notes': '',
  'state': 'IN',
  'zip': '46168'},
 'IND4': {'address': '710 S. Girls School Rd',
  'city': 'Indianapolis',
  'code': 'IND4',
  'notes': '902850',
  'state': 'IN',
  'zip': '46231'},
 'IND5': {'address': '800 Perry Road',
  'city': 'Plainfield',
  'code': 'IND5',
  'notes': '925800',
  'state': 'IN',
  'zip': '46168'},
 'IND6': {'address': '1453 10th Street',
  'city': 'Jeffersonville',
  'code': 'IND6',
  'notes': '',
  'state': 'IN',
  'zip': '47130'},
 'IND7': {'address': '9101 Orly Drive',
  'city': 'Indianapolis',
  'code': 'IND7',
  'notes': '',
  'state': 'IN',
  'zip': '46241'},
 'ISE2': {'address': '1227 124th Ave NE Building 2 Suite A200',
  'city': 'Bellevue',
  'code': 'ISE2',
  'notes': '',
  'state': 'WA',
  'zip': '98004'},
 'ITX1': {'address': '',
  'city': 'Houston',
  'code': 'ITX1',
  'notes': '',
  'state': 'TX',
  'zip': '77064'},
 'ITX2': {'address': '',
  'city': 'Houston',
  'code': 'ITX2',
  'notes': '',
  'state': 'TX',
  'zip': '77040'},
 'IVSA': {'address': '4620 Olympic Blvd',
  'city': 'Erlanger',
  'code': 'IVSA',
  'notes': '',
  'state': 'KY',
  'zip': '41018'},
 'IVSB': {'address': '3521 Point Pleasant Rd',
  'city': 'Hebron',
  'code': 'IVSB',
  'notes': '264000',
  'state': 'KY',
  'zip': '41048'},
 'IVSC': {'address': '286 Mantua Grove Rd',
  'city': 'West Deptford',
  'code': 'IVSC',
  'notes': '',
  'state': 'NJ',
  'zip': '8066'},
 'IVSD': {'address': '800 Arlington Blvd',
  'city': 'Swedesboro',
  'code': 'IVSD',
  'notes': '',
  'state': 'NJ',
  'zip': '8085'},
 'IVSE': {'address': '2951 Marion Dr, Ste 101-103',
  'city': 'Las Vegas',
  'code': 'IVSE',
  'notes': '',
  'state': 'NV',
  'zip': '89115'},
 'IVSF': {'address': '2821 Marion Dr, Ste 109',
  'city': 'Las Vegas',
  'code': 'IVSF',
  'notes': '',
  'state': 'NV',
  'zip': '89115'},
 'JAX1': {'address': '12900 Pecan Park Road',
  'city': 'Jacksonville',
  'code': 'JAX1',
  'notes': '1600000',
  'state': 'FL',
  'zip': '32218'},
 'JAX2': {'address': '12900 Pecan Park Road',
  'city': 'Jacksonville',
  'code': 'JAX2',
  'notes': '',
  'state': 'FL',
  'zip': '32218'},
 'JAX3': {'address': '13333 103rd St',
  'city': 'Jacksonville',
  'code': 'JAX3',
  'notes': '',
  'state': 'FL',
  'zip': '32221'},
 'JAX5': {'address': '4948 Bulls Bay Hwy',
  'city': 'Jacksonville',
  'code': 'JAX5',
  'notes': '237000',
  'state': 'FL',
  'zip': '32219'},
 'JFK7': {'address': '7 W. 34th St.',
  'city': 'New York',
  'code': 'JFK7',
  'notes': '40000',
  'state': 'NY',
  'zip': '10001'},
 'JFK8': {'address': '546 GULF AVE.',
  'city': 'STATEN ISLAND',
  'code': 'JFK8',
  'notes': '',
  'state': 'NY',
  'zip': '10314'},
 'LAL1': {'address': '1760 County Line Rd.',
  'city': 'Lakeland',
  'code': 'LAL1',
  'notes': '',
  'state': 'FL',
  'zip': '33811'},
 'LAS2': {'address': '3837 Bay Lake Trail, Suite 111 North',
  'city': 'Las Vegas',
  'code': 'LAS2',
  'notes': '283920',
  'state': 'NV',
  'zip': '89030'},
 'LAS5': {'address': '4410 Nexus Way',
  'city': 'Las Vegas',
  'code': 'LAS5',
  'notes': '',
  'state': 'NV',
  'zip': '89115'},
 'LAS6': {'address': '4550 Nexus Way',
  'city': 'North Las Vegas',
  'code': 'LAS6',
  'notes': '',
  'state': 'NV',
  'zip': '89115'},
 'LASX': {'address': 'North Lamb Blvd and Tropical Parkway',
  'city': 'North Las Vegas',
  'code': 'LASX',
  'notes': '813100',
  'state': 'NV',
  'zip': '89081'},
 'LAX2': {'address': '5650 DOLLY AVE.',
  'city': 'BUENA PARK',
  'code': 'LAX2',
  'notes': '',
  'state': 'CA',
  'zip': '90621'},
 'LAX5': {'address': '6400 Valley View St',
  'city': 'BUENA PARK',
  'code': 'LAX5',
  'notes': '238270',
  'state': 'CA',
  'zip': '90620'},
 'LAX6': {'address': '5119 District Blvd',
  'city': 'Los Angeles',
  'code': 'LAX6',
  'notes': '',
  'state': 'CA',
  'zip': '90058'},
 'LCK1': {'address': '',
  'city': 'Obetz',
  'code': 'LCK1',
  'notes': '1000000',
  'state': 'OH',
  'zip': '43207'},
 'LEX1': {'address': '1850 Mercer Drive',
  'city': 'Lexington',
  'code': 'LEX1',
  'notes': '604000',
  'state': 'KY',
  'zip': '40511'},
 'LEX2': {'address': '172 Trade St.',
  'city': 'Lexington',
  'code': 'LEX2',
  'notes': '380000',
  'state': 'KY',
  'zip': '40511'},
 'LEX3': {'address': '1850 Mercer Rd',
  'city': 'Lexington',
  'code': 'LEX3',
  'notes': '',
  'state': 'KY',
  'zip': '40511'},
 'LGA6': {'address': '8003 Industrial Avenue',
  'city': 'Carteret',
  'code': 'LGA6',
  'notes': '',
  'state': 'NJ',
  'zip': '7008'},
 'LGA7': {'address': '380 Middlesex Avenue',
  'city': 'Carteret',
  'code': 'LGA7',
  'notes': '794400',
  'state': 'NJ',
  'zip': '7008'},
 'LGA8': {'address': '380 Middlesex Avenue',
  'city': 'Carteret',
  'code': 'LGA8',
  'notes': '161400',
  'state': 'NJ',
  'zip': '7008'},
 'LGA9': {'address': '2170 State Route 27',
  'city': 'Edison',
  'code': 'LGA9',
  'notes': '923000',
  'state': 'NJ',
  'zip': '8817'},
 'LGB1': {'address': '2417 E. Carson St',
  'city': 'Long Beach',
  'code': 'LGB1',
  'notes': '',
  'state': 'CA',
  'zip': '90810'},
 'LGB3': {'address': '4950 Goodman Way',
  'city': 'Eastvale',
  'code': 'LGB3',
  'notes': '',
  'state': 'CA',
  'zip': '92880'},
 'LGB4': {'address': '27517 Pioneer Ave',
  'city': 'Redlands',
  'code': 'LGB4',
  'notes': '',
  'state': 'CA',
  'zip': '92374'},
 'LGB6': {'address': '20901 Krameria Ave',
  'city': 'Riverside',
  'code': 'LGB6',
  'notes': '1000000',
  'state': 'CA',
  'zip': '92518'},
 'LGB8': {'address': '1568 N Linden Ave',
  'city': 'RIALTO',
  'code': 'LGB8',
  'notes': '',
  'state': 'CA',
  'zip': '92376'},
 'MC05': {'address': '305 Deen Still Road',
  'city': 'Davenport',
  'code': 'MC05',
  'notes': '270000',
  'state': 'FL',
  'zip': '33897'},
 'MCI1': {'address': '16851 W 113th St',
  'city': 'Lenexa',
  'code': 'MCI1',
  'notes': '',
  'state': 'KS',
  'zip': '66219'},
 'MCI5': {'address': '16851 W 113th St. Lenexa Logistics Center',
  'city': 'Lenexa',
  'code': 'MCI5',
  'notes': '267000',
  'state': 'KS',
  'zip': '66219'},
 'MCI7': {'address': '27200 W 157th St',
  'city': 'New Century',
  'code': 'MCI7',
  'notes': '446500',
  'state': 'KS',
  'zip': '66031'},
 'MCIX': {'address': '113th Street and Renner Boulevard',
  'city': 'Lenexa',
  'code': 'MCIX',
  'notes': '',
  'state': 'KS',
  'zip': '66219'},
 'MCO1': {'address': '12340 Boggy Creek Rd',
  'city': 'Orlando',
  'code': 'MCO1',
  'notes': '',
  'state': 'FL',
  'zip': '32824'},
 'MCO5': {'address': '205 Deen Still Road',
  'city': 'Davenport',
  'code': 'MCO5',
  'notes': '270000',
  'state': 'FL',
  'zip': '33897'},
 'MDT1': {'address': '2 Ames Drive',
  'city': 'Carlisle',
  'code': 'MDT1',
  'notes': '750000',
  'state': 'PA',
  'zip': '17015'},
 'MDT2': {'address': '600 Principio Parkway',
  'city': 'North East',
  'code': 'MDT2',
  'notes': '1148900',
  'state': 'MD',
  'zip': '21901'},
 'MDW1': {'address': 'Greater Chicago Area',
  'city': 'Joliet',
  'code': 'MDW1',
  'notes': '700000',
  'state': 'IL',
  'zip': '60433'},
 'MDW2': {'address': '250 Emerald Drive',
  'city': 'Joliet',
  'code': 'MDW2',
  'notes': '475104',
  'state': 'IL',
  'zip': '60433'},
 'MDW4': {'address': '201 EMERALD DR',
  'city': 'Joliet',
  'code': 'MDW4',
  'notes': '1000000',
  'state': 'IL',
  'zip': '60433'},
 'MDW5': {'address': '1111 N. Cherry Ave.',
  'city': 'Goose Island',
  'code': 'MDW5',
  'notes': '52000',
  'state': 'IL',
  'zip': '60642'},
 'MDW6': {'address': '1125 W REMINGTON BLVD',
  'city': 'Romeoville',
  'code': 'MDW6',
  'notes': '767273',
  'state': 'IL',
  'zip': '60446'},
 'MDW7': {'address': '6521 W Monee Manhattan Road',
  'city': 'Monee',
  'code': 'MDW7',
  'notes': '856600',
  'state': 'IL',
  'zip': '60449'},
 'MDW8': {'address': '1750 Bridge Drive',
  'city': 'Waukegan',
  'code': 'MDW8',
  'notes': '626800',
  'state': 'IL',
  'zip': '60449'},
 'MDW9': {'address': '2806 Duke Parkway',
  'city': 'Aurora',
  'code': 'MDW9',
  'notes': '',
  'state': 'IL',
  'zip': '60504'},
 'MDWX': {'address': '2801 S. Western Ave',
  'city': 'Chicago',
  'code': 'MDWX',
  'notes': '150000',
  'state': 'IL',
  'zip': '60608'},
 'MDWY': {'address': 'Route 59',
  'city': 'Aurora',
  'code': 'MDWY',
  'notes': '1000000',
  'state': 'IL',
  'zip': '60563'},
 'MDWZ': {'address': 'Route 59',
  'city': 'Aurora',
  'code': 'MDWZ',
  'notes': '400000',
  'state': 'IL',
  'zip': '60563'},
 'MEM1': {'address': '3292 E Holmes Rd',
  'city': 'Memphis',
  'code': 'MEM1',
  'notes': '',
  'state': 'TN',
  'zip': '38118'},
 'MEM5': {'address': '5155 CITATION DR.',
  'city': 'MEMPHIS',
  'code': 'MEM5',
  'notes': '',
  'state': 'TN',
  'zip': '38118'},
 'MGE1': {'address': '650 Broadway Avenue',
  'city': 'Braselton',
  'code': 'MGE1',
  'notes': '',
  'state': 'GA',
  'zip': '30517'},
 'MGE3': {'address': '808 Hog Mountain Road',
  'city': 'Jefferson',
  'code': 'MGE3',
  'notes': '',
  'state': 'GA',
  'zip': '30549'},
 'MGE5': {'address': '235 HOG MOUNTAIN RD',
  'city': 'JEFFERSON',
  'code': 'MGE5',
  'notes': '',
  'state': 'GA',
  'zip': '30549'},
 'MGE7': {'address': '650 Broadway Avenue',
  'city': 'Braselton',
  'code': 'MGE7',
  'notes': '',
  'state': 'GA',
  'zip': '30517'},
 'MIA1': {'address': '14000 NW 37TH AVE.',
  'city': 'OPA-LOCKA',
  'code': 'MIA1',
  'notes': '',
  'state': 'FL',
  'zip': '33054'},
 'MIA5': {'address': '1900 NW 132nd Place',
  'city': 'Doral (Miami)',
  'code': 'MIA5',
  'notes': '335800',
  'state': 'FL',
  'zip': '33182'},
 'MIA6': {'address': '3200 NW 67th Avenue',
  'city': 'Miami',
  'code': 'MIA6',
  'notes': '',
  'state': 'FL',
  'zip': '33122'},
 'MKC4': {'address': '19645 Waverly Rd',
  'city': 'Edgerton',
  'code': 'MKC4',
  'notes': '822100',
  'state': 'KS',
  'zip': '66021'},
 'MKC6': {'address': '6925 Riverview Ave',
  'city': 'Kansas City',
  'code': 'MKC6',
  'notes': '',
  'state': 'KS',
  'zip': '66102'},
 'MKE1': {'address': '3501 120th Ave',
  'city': 'Kenosha',
  'code': 'MKE1',
  'notes': '1100000',
  'state': 'WI',
  'zip': '53144'},
 'MKE5': {'address': '11211 Burlington Road',
  'city': 'Kenosha',
  'code': 'MKE5',
  'notes': '600000',
  'state': 'WI',
  'zip': '53144'},
 'MOB5': {'address': '6735 Trippel Road',
  'city': 'Mobile',
  'code': 'MOB5',
  'notes': '',
  'state': 'AL',
  'zip': '36619'},
 'MSP1': {'address': '2601 4th Avenue East',
  'city': 'Shakopee',
  'code': 'MSP1',
  'notes': '820000',
  'state': 'MN',
  'zip': '55379'},
 'MSP5': {'address': '5825 11th Ave. East',
  'city': 'Shakopee',
  'code': 'MSP5',
  'notes': '162000',
  'state': 'MN',
  'zip': '55379'},
 'MSP9': {'address': '9001 Wyoming Ave. North',
  'city': 'Brooklyn Park',
  'code': 'MSP9',
  'notes': '',
  'state': 'MN',
  'zip': '55445'},
 'OAK3': {'address': '255 Park Center Drive',
  'city': 'Patterson',
  'code': 'OAK3',
  'notes': '1000000',
  'state': 'CA',
  'zip': '95363'},
 'OAK4': {'address': '1555 N. Chrisman Rd',
  'city': 'Tracy',
  'code': 'OAK4',
  'notes': '1200000',
  'state': 'CA',
  'zip': '95304'},
 'OAK5': {'address': '38811 Cherry Street',
  'city': 'Newark',
  'code': 'OAK5',
  'notes': '574650',
  'state': 'CA',
  'zip': '94560'},
 'OAK6': {'address': '1350 N. MacArthur Drive',
  'city': 'Tracy',
  'code': 'OAK6',
  'notes': '',
  'state': 'CA',
  'zip': '95304'},
 'OAK7': {'address': '38811 Cherry St',
  'city': 'Newark',
  'code': 'OAK7',
  'notes': '',
  'state': 'CA',
  'zip': '94560'},
 'OAK8': {'address': '1 Middleton Way',
  'city': 'American Canyon',
  'code': 'OAK8',
  'notes': '',
  'state': 'CA',
  'zip': '94503'},
 'OKC5': {'address': '1414 S. Council Rd',
  'city': 'Oklahoma City',
  'code': 'OKC5',
  'notes': '',
  'state': 'OK',
  'zip': '73179'},
 'ONT2': {'address': '1910 E Central Ave',
  'city': 'San Bernardino',
  'code': 'ONT2',
  'notes': '951700',
  'state': 'CA',
  'zip': '92408'},
 'ONT3': {'address': '1910 E. Central Ave.',
  'city': 'San Bernadino',
  'code': 'ONT3',
  'notes': '',
  'state': 'CA',
  'zip': '92408'},
 'ONT4': {'address': '1910 E Central Ave',
  'city': 'San Bernardino',
  'code': 'ONT4',
  'notes': '514600',
  'state': 'CA',
  'zip': '92408'},
 'ONT5': {'address': '2020 E. Central Ave. Bldg. 4',
  'city': 'San Bernardino',
  'code': 'ONT5',
  'notes': '514600',
  'state': 'CA',
  'zip': '92408'},
 'ONT6': {'address': '24208 San Michele Rd',
  'city': 'Moreno Valley',
  'code': 'ONT6',
  'notes': '1250000',
  'state': 'CA',
  'zip': '92551'},
 'ONT7': {'address': '2020 E Central Ave',
  'city': 'San Bernardino',
  'code': 'ONT7',
  'notes': '514600',
  'state': 'CA',
  'zip': '92408'},
 'ONT8': {'address': '24300 Nandina Ave',
  'city': 'Moreno Valley',
  'code': 'ONT8',
  'notes': '769300',
  'state': 'CA',
  'zip': '92551'},
 'ONT9': {'address': '2125 West San Bernardino Ave',
  'city': 'Redlands',
  'code': 'ONT9',
  'notes': '700000',
  'state': 'CA',
  'zip': '92374'},
 'ORD6': {'address': '1250 Mittel Blvd',
  'city': 'Wood Dale',
  'code': 'ORD6',
  'notes': '82100',
  'state': 'IL',
  'zip': '60191'},
 'ORF1': {'address': '3516 South Military Hwy',
  'city': 'Chesapeake',
  'code': 'ORF1',
  'notes': '',
  'state': 'VA',
  'zip': '23323'},
 'PCA1': {'address': '1565 N MacArthur Drive',
  'city': 'Tracy',
  'code': 'PCA1',
  'notes': '',
  'state': 'CA',
  'zip': '95376'},
 'PCA2': {'address': '1650 East Central Avenue',
  'city': 'San Bernardino',
  'code': 'PCA2',
  'notes': '',
  'state': 'CA',
  'zip': '92408'},
 'PDX5': {'address': '5647 NW Huffman Street',
  'city': 'Washington, Hillsboro',
  'code': 'PDX5',
  'notes': '303000',
  'state': 'OR',
  'zip': '97124'},
 'PDX6': {'address': '15000 N Lombard St',
  'city': 'Portland',
  'code': 'PDX6',
  'notes': '',
  'state': 'OR',
  'zip': '97203'},
 'PDX7': {'address': '4775 Depot Ct SE',
  'city': 'Salem',
  'code': 'PDX7',
  'notes': '',
  'state': 'OR',
  'zip': '97317'},
 'PDX9': {'address': '1250 NW Swigert Way',
  'city': 'Troutdale',
  'code': 'PDX9',
  'notes': '',
  'state': 'OR',
  'zip': '97060'},
 'PFL1': {'address': '1001 13th Avenue East',
  'city': 'Bradenton',
  'code': 'PFL1',
  'notes': '',
  'state': 'FL',
  'zip': '34208'},
 'PGA1': {'address': '6200 Fulton Industrial Blvd',
  'city': 'Atlanta',
  'code': 'PGA1',
  'notes': '',
  'state': 'GA',
  'zip': '30336'},
 'PHL1': {'address': '1 Centerpoint Blvd.',
  'city': 'New Castle',
  'code': 'PHL1',
  'notes': '202000',
  'state': 'DE',
  'zip': '19720'},
 'PHL3': {'address': '1600 Johnson Way',
  'city': 'New Castle',
  'code': 'PHL3',
  'notes': '',
  'state': 'DE',
  'zip': '19720'},
 'PHL4': {'address': '21 Roadway Dr',
  'city': 'Carlisle',
  'code': 'PHL4',
  'notes': '558700',
  'state': 'PA',
  'zip': '17015'},
 'PHL5': {'address': '500 McCarthy Dr. Fairview Business Park',
  'city': 'Lewisberry',
  'code': 'PHL5',
  'notes': '750000',
  'state': 'PA',
  'zip': '17339'},
 'PHL6': {'address': '675 Allen Rd',
  'city': 'Carlisle',
  'code': 'PHL6',
  'notes': '1206500',
  'state': 'PA',
  'zip': '17015'},
 'PHL7': {'address': '560 Merrimac Ave',
  'city': 'Middletown',
  'code': 'PHL7',
  'notes': '1200000',
  'state': 'DE',
  'zip': '19709'},
 'PHL8': {'address': '727 N. Broad Street',
  'city': 'Middletown',
  'code': 'PHL8',
  'notes': '',
  'state': 'DE',
  'zip': '19709'},
 'PHL9': {'address': '2 Ames Drive',
  'city': 'Carlisle',
  'code': 'PHL9',
  'notes': '',
  'state': 'PA',
  'zip': '17015'},
 'PHX3': {'address': '6835 West Buckeye Road',
  'city': 'Pheonix',
  'code': 'PHX3',
  'notes': '1005000',
  'state': 'AZ',
  'zip': '85043'},
 'PHX5': {'address': '16980 W Commerce Drive',
  'city': 'Goodyear',
  'code': 'PHX5',
  'notes': '1200000',
  'state': 'AZ',
  'zip': '85338'},
 'PHX6': {'address': '4750 West Mohave St',
  'city': 'Pheonix',
  'code': 'PHX6',
  'notes': '1207000',
  'state': 'AZ',
  'zip': '85043'},
 'PHX7': {'address': '800 N 75th Ave',
  'city': 'Pheonix',
  'code': 'PHX7',
  'notes': '1260000',
  'state': 'AZ',
  'zip': '85043'},
 'PHX8': {'address': '800 N 75th Ave',
  'city': 'Phoenix',
  'code': 'PHX8',
  'notes': '',
  'state': 'AZ',
  'zip': '85043'},
 'PHX9': {'address': '777 S 79th Ave',
  'city': 'Tolleson',
  'code': 'PHX9',
  'notes': '',
  'state': 'AZ',
  'zip': '85353'},
 'PICV': {'address': '1155 Worldwide Blvd.',
  'city': 'Hebron',
  'code': 'PICV',
  'notes': '',
  'state': 'KY',
  'zip': '41048'},
 'PIL1': {'address': '801 Midpoint Road',
  'city': 'Minooka',
  'code': 'PIL1',
  'notes': '',
  'state': 'IL',
  'zip': '60447'},
 'PIN1': {'address': '6161 Decatur Blvd',
  'city': 'Indianapolis',
  'code': 'PIN1',
  'notes': '',
  'state': 'IN',
  'zip': '46421'},
 'PISA': {'address': '900 Patrol Rd',
  'city': 'Jeffersonville',
  'code': 'PISA',
  'notes': '',
  'state': 'IN',
  'zip': '47130'},
 'PISB': {'address': '376 Zappos.com Blvd',
  'city': 'Shepherdsville',
  'code': 'PISB',
  'notes': '',
  'state': 'KY',
  'zip': '40165'},
 'PISC': {'address': '271 Omega Parkway',
  'city': 'Shepherdsville',
  'code': 'PISC',
  'notes': '',
  'state': 'KY',
  'zip': '40165'},
 'PIT1': {'address': '2250 Roswell Drive',
  'city': 'Pittsburgh',
  'code': 'PIT1',
  'notes': '',
  'state': 'PA',
  'zip': '15205'},
 'PIT5': {'address': '2250 Roswell Drive',
  'city': 'Pittsburg',
  'code': 'PIT5',
  'notes': '250000',
  'state': 'PA',
  'zip': '15205'},
 'PNE5': {'address': '18 APPLEGATE DR.',
  'city': 'ROBBINSVILLE',
  'code': 'PNE5',
  'notes': '',
  'state': 'NJ',
  'zip': '8691'},
 'POH1': {'address': '3880 Groveport Road',
  'city': 'Obetz',
  'code': 'POH1',
  'notes': '',
  'state': 'OH',
  'zip': '43207'},
 'PPA1': {'address': '545 Oak Hill Road',
  'city': 'Mountaintop',
  'code': 'PPA1',
  'notes': '',
  'state': 'PA',
  'zip': '18707'},
 'PTX1': {'address': '2101 Danieldale Road',
  'city': 'Lancaster',
  'code': 'PTX1',
  'notes': '',
  'state': 'TX',
  'zip': '75134'},
 'PWA1': {'address': '2309 Milwaukee Way',
  'city': 'Tacoma',
  'code': 'PWA1',
  'notes': '',
  'state': 'WA',
  'zip': '98421'},
 'RDU5': {'address': '1805 TW Alexander Drive',
  'city': 'Durham',
  'code': 'RDU5',
  'notes': '324500',
  'state': 'NC',
  'zip': '27703'},
 'RIC1': {'address': '5000 Commerce Way',
  'city': 'Petersburg',
  'code': 'RIC1',
  'notes': '1100000',
  'state': 'VA',
  'zip': '23803'},
 'RIC2': {'address': '1901 Meadowville Technology Pkwy',
  'city': 'Chester',
  'code': 'RIC2',
  'notes': '1100000',
  'state': 'VA',
  'zip': '23836'},
 'RIC3': {'address': '1901 Meadowville Technology Parkway',
  'city': 'Chesterfield',
  'code': 'RIC3',
  'notes': '',
  'state': 'VA',
  'zip': '23836'},
 'RIC5': {'address': '11600 East Lakeridge Parkway',
  'city': 'Ashland',
  'code': 'RIC5',
  'notes': '',
  'state': 'VA',
  'zip': '23005'},
 'RNO1': {'address': '1600 East Newlands Drive',
  'city': 'Fernley',
  'code': 'RNO1',
  'notes': '786000',
  'state': 'NV',
  'zip': '89408'},
 'RNO2': {'address': '8000 North Virginia Street Reno',
  'city': 'Reno',
  'code': 'RNO2',
  'notes': '634000',
  'state': 'NV',
  'zip': '85906'},
 'RNO3': {'address': '555 Milan Dr',
  'city': 'Sparks',
  'code': 'RNO3',
  'notes': '566900',
  'state': 'NV',
  'zip': '89434'},
 'RNO4': {'address': '8000 North Virginia Street',
  'city': 'Reno',
  'code': 'RNO4',
  'notes': '634000',
  'state': 'NV',
  'zip': '89506'},
 'SAT1': {'address': '6000 Enterprise Avenue',
  'city': 'Schertz',
  'code': 'SAT1',
  'notes': '1260000',
  'state': 'TX',
  'zip': '78154'},
 'SAT2': {'address': '1401 E McCarty Lane',
  'city': 'San Marcos',
  'code': 'SAT2',
  'notes': '885000',
  'state': 'TX',
  'zip': '78666'},
 'SAT5': {'address': '1410 S. Callaghan Road',
  'city': 'Bexar. San Antonio',
  'code': 'SAT5',
  'notes': '193900',
  'state': 'TX',
  'zip': '78227'},
 'SAV1': {'address': 'Georgia Ports Authority Garden City Terminal, Building CFS #2',
  'city': 'Garden City',
  'code': 'SAV1',
  'notes': '',
  'state': 'GA',
  'zip': '31408'},
 'SAV3': {'address': '7001 Skipper Rd',
  'city': 'Macon',
  'code': 'SAV3',
  'notes': '',
  'state': 'GA',
  'zip': '31216'},
 'SDF1': {'address': '1050 South Columbia',
  'city': 'Campbellsville',
  'code': 'SDF1',
  'notes': '770000',
  'state': 'KY',
  'zip': '42718'},
 'SDF2': {'address': '4360 Robards Ln',
  'city': 'Louisville',
  'code': 'SDF2',
  'notes': '110000',
  'state': 'KY',
  'zip': '40218'},
 'SDF4': {'address': '376 Zappos.com Blvd',
  'city': 'Shepherdsville',
  'code': 'SDF4',
  'notes': '823000',
  'state': 'KY',
  'zip': '40165'},
 'SDF6': {'address': '271 Omega Pkwy',
  'city': 'Shepherdsville',
  'code': 'SDF6',
  'notes': '118000',
  'state': 'KY',
  'zip': '40165'},
 'SDF7': {'address': '300 Omicron Court',
  'city': 'Shepherdsville',
  'code': 'SDF7',
  'notes': '281000',
  'state': 'KY',
  'zip': '40165'},
 'SDF8': {'address': '900 Patrol Rd',
  'city': 'Jeffersonville',
  'code': 'SDF8',
  'notes': '1200000',
  'state': 'IN',
  'zip': '47130'},
 'SDF9': {'address': '100 W. Thomas P. Echols Lane',
  'city': 'Shepherdsville',
  'code': 'SDF9',
  'notes': '600000',
  'state': 'KY',
  'zip': '40165'},
 'SEA6': {'address': '2646 Rainier Ave. South',
  'city': 'Seattle',
  'code': 'SEA6',
  'notes': '313300',
  'state': 'WA',
  'zip': '98144'},
 'SEA8': {'address': '124th Ave NE Building 2 Suite A200',
  'city': 'Bellevue',
  'code': 'SEA8',
  'notes': '',
  'state': 'WA',
  'zip': '98004'},
 'SJC7': {'address': '188 Mountain House Parkway',
  'city': 'Tracy',
  'code': 'SJC7',
  'notes': '',
  'state': 'CA',
  'zip': '95391'},
 'SLC1': {'address': '777 North 5600 West',
  'city': 'Salt Lake City',
  'code': 'SLC1',
  'notes': '',
  'state': 'UT',
  'zip': '84116'},
    'SLC1x': {'address': '777 N 5600 W',
    'city': 'Salt Lake City',
    'code': 'SLC1',
    'notes': '',
    'state': 'UT',
    'zip': '84116'},
 'SLT7': {'address': '3931 Lakeview Corporate Dr.',
  'city': 'Edwarsville',
  'code': 'SLT7',
  'notes': '',
  'state': 'IL',
  'zip': '62025'},
 'SMF1': {'address': '4900 W Elkhorn Blvd',
  'city': 'Sacramento',
  'code': 'SMF1',
  'notes': '',
  'state': 'CA',
  'zip': '95835'},
 'SMF3': {'address': '1540 Zephyr St',
  'city': 'STOCKTON',
  'code': 'SMF3',
  'notes': '',
  'state': 'CA',
  'zip': '95206'},
 'SMF5': {'address': '300 Crocker Dr',
  'city': 'VACAVILLE',
  'code': 'SMF5',
  'notes': '231993',
  'state': 'CA',
  'zip': '95688'},
 'SNA4': {'address': '2496 W Walnut Ave',
  'city': 'Rialto',
  'code': 'SNA4',
  'notes': '882200',
  'state': 'CA',
  'zip': '92376'},
 'SNA6': {'address': '5250 Goodman Road',
  'city': 'Eastvale',
  'code': 'SNA6',
  'notes': '1007700',
  'state': 'CA',
  'zip': '92880'},
 'SNA7': {'address': '555 East Orange Show Rd',
  'city': 'San Bernardino',
  'code': 'SNA7',
  'notes': '',
  'state': 'CA',
  'zip': '92408'},
 'SNA8': {'address': '555 East Orange Show Rd',
  'city': 'San Bernardino',
  'code': 'SNA8',
  'notes': '1102600',
  'state': 'CA',
  'zip': '92408'},
 'SNA9': {'address': '5250 Goodman Road',
  'city': 'Eastvale',
  'code': 'SNA9',
  'notes': '',
  'state': 'CA',
  'zip': '92880'},
 'STL4': {'address': '3050 Gateway Commerce Center Dr S',
  'city': 'Edwardsville',
  'code': 'STL4',
  'notes': '769500',
  'state': 'IL',
  'zip': '62025'},
 'STL5': {'address': '462 Hazelwood Logistics Center Dr',
  'city': 'Hazelwood',
  'code': 'STL5',
  'notes': '348480',
  'state': 'MO',
  'zip': '63042'},
 'STL6': {'address': '3931 Lakeview Corporate Drive',
  'city': 'Edwardsville',
  'code': 'STL6',
  'notes': '700000',
  'state': 'IL',
  'zip': '62025'},
 'STL7': {'address': '3931 Lakeview Corporate Drive',
  'city': 'Edwardsville',
  'code': 'STL7',
  'notes': '',
  'state': 'IL',
  'zip': '62025'},
 'SUOC': {'address': '8750 Larkin Rd',
  'city': 'Savage',
  'code': 'SUOC',
  'notes': '',
  'state': 'MD',
  'zip': '20763'},
 'SUOD': {'address': '121 Kelsey Ln',
  'city': 'Tampa',
  'code': 'SUOD',
  'notes': '',
  'state': 'FL',
  'zip': '33619'},
 'SUOE': {'address': '74 Kenny Pl',
  'city': 'Saddle Brook',
  'code': 'SUOE',
  'notes': '',
  'state': 'NJ',
  'zip': '7663'},
 'TAM1': {'address': '2800 S Texas Avenue Suite 401',
  'city': 'Bryan',
  'code': 'TAM1',
  'notes': '',
  'state': 'TX',
  'zip': '77802'},
 'TBD2': {'address': '1111 N Cherry Ave',
  'city': 'Goose Island',
  'code': 'TBD2',
  'notes': '51970',
  'state': 'IL',
  'zip': '60642'},
 'TBD3': {'address': '401 E Laraway Road',
  'city': 'Joliet',
  'code': 'TBD3',
  'notes': '475104',
  'state': 'IL',
  'zip': '40433'},
 'TBD5': {'address': '8003 Industrial Ave, Building A',
  'city': 'Carteret',
  'code': 'TBD5',
  'notes': '1064515',
  'state': 'NJ',
  'zip': '8085'},
 'TBD6': {'address': '4800 LBJ Freeway',
  'city': 'Dallas',
  'code': 'TBD6',
  'notes': '500000',
  'state': 'TX',
  'zip': '75241'},
 'TBD7': {'address': '2801 S. Western Ave',
  'city': 'Chicago',
  'code': 'TBD7',
  'notes': '150000',
  'state': 'IL',
  'zip': '60608'},
 'TBD8': {'address': 'Etna Township Park',
  'city': 'Etna',
  'code': 'TBD8',
  'notes': '800000',
  'state': 'OH',
  'zip': '43062'},
 'TBD9': {'address': 'Alum Creek Drive',
  'city': 'Obetz',
  'code': 'TBD9',
  'notes': '1000000',
  'state': 'OH',
  'zip': '43207'},
 'TBDA': {'address': '1300 East McCarty Lane',
  'city': 'San Marcos',
  'code': 'TBDA',
  'notes': '85000',
  'state': 'TX',
  'zip': '78666'},
 'TBDB': {'address': '2 Empire Boulevard',
  'city': 'Moonachie',
  'code': 'TBDB',
  'notes': '75000',
  'state': 'NJ',
  'zip': '7074'},
 'TEB3': {'address': '2651 Oldmans Creek Rd',
  'city': 'Logan Township',
  'code': 'TEB3',
  'notes': '',
  'state': 'NJ',
  'zip': '8085'},
 'TEB6': {'address': '22 Highstown-Cranbury Station Rd',
  'city': 'Cranbury Township',
  'code': 'TEB6',
  'notes': '',
  'state': 'NJ',
  'zip': '8512'},
 'TFC1': {'address': '5050 West Mohave St',
  'city': 'Pheonix',
  'code': 'TFC1',
  'notes': '1',
  'state': 'AZ',
  'zip': '85043'},
 'TIL1': {'address': '1111 N Cherry Street',
  'city': 'Chicago',
  'code': 'TIL1',
  'notes': '',
  'state': 'IL',
  'zip': '60642'},
 'TPA1': {'address': '3350 Laurel Ridge Ave',
  'city': 'Ruskin',
  'code': 'TPA1',
  'notes': '1100000',
  'state': 'FL',
  'zip': '33570'},
 'TPA2': {'address': '1760 County Line Rd.',
  'city': 'Lakeland',
  'code': 'TPA2',
  'notes': '1000000',
  'state': 'FL',
  'zip': '33811'},
 'TTN1': {'address': '',
  'city': 'Florence',
  'code': 'TTN1',
  'notes': '800000',
  'state': 'NJ',
  'zip': '8518'},
 'TTX2': {'address': '2209 Rutland Dr Ste B110',
  'city': 'Austin',
  'code': 'TTX2',
  'notes': '',
  'state': 'TX',
  'zip': '78758'},
 'TTX3': {'address': '4221 Way Out West Drive',
  'city': 'Houston',
  'code': 'TTX3',
  'notes': '',
  'state': 'TX',
  'zip': '77092'},
 'TTX4': {'address': '6627 Maple Avenue',
  'city': 'Dallas',
  'code': 'TTX4',
  'notes': '',
  'state': 'TX',
  'zip': '75235'},
 'TUL1': {'address': '2654 North Highway 169',
  'city': 'Coffeyville',
  'code': 'TUL1',
  'notes': '750000',
  'state': 'KS',
  'zip': '67337'},
 'TUS1': {'address': '533 W Lower Buckey Road',
  'city': 'Phoenix',
  'code': 'TUS1',
  'notes': '',
  'state': 'AZ',
  'zip': '85043'},
 'TWA0': {'address': '13537 Aurora Ave N',
  'city': 'Seattle',
  'code': 'TWA0',
  'notes': '',
  'state': 'WA',
  'zip': '98133'},
 'UAZ1': {'address': '',
  'city': 'Phoenix',
  'code': 'UAZ1',
  'notes': '',
  'state': 'AZ',
  'zip': '85001'},
 'UCA1': {'address': '888 Tennessee Street',
  'city': 'San Francisco',
  'code': 'UCA1',
  'notes': '39000',
  'state': 'CA',
  'zip': '94112'},
 'UCA2': {'address': '',
  'city': 'Redondo Beach',
  'code': 'UCA2',
  'notes': '',
  'state': 'CA',
  'zip': '90277'},
 'UCA3': {'address': '11800 W Olympic Blvd.',
  'city': 'Los Angeles',
  'code': 'UCA3',
  'notes': '28800',
  'state': 'CA',
  'zip': '90064'},
 'UCA4': {'address': '2006 McGaw Ave.',
  'city': 'Irvine',
  'code': 'UCA4',
  'notes': '45300',
  'state': 'CA',
  'zip': '92614'},
 'UCA5': {'address': 'Silver Lake',
  'city': 'Silver Lake',
  'code': 'UCA5',
  'notes': '',
  'state': 'CA',
  'zip': '90001'},
 'UCA6': {'address': '2727 Kurtz St.',
  'city': 'San Diego',
  'code': 'UCA6',
  'notes': '37800',
  'state': 'CA',
  'zip': '92110'},
 'UCA7': {'address': '222 Commercial Street',
  'city': 'Sunnyvale',
  'code': 'UCA7',
  'notes': '24000',
  'state': 'CA',
  'zip': '94085'},
 'UCA8': {'address': '3100 San Pablo Ave. Ste 120',
  'city': 'West Berkley',
  'code': 'UCA8',
  'notes': '21000',
  'state': 'CA',
  'zip': '94702'},
 'UCA9': {'address': '2934 Ramona Avenue',
  'city': 'Sacramento',
  'code': 'UCA9',
  'notes': '20000',
  'state': 'CA',
  'zip': '95826'},
 'UCO1': {'address': '480 E 55th Ave Suite 100',
  'city': 'Denver',
  'code': 'UCO1',
  'notes': '',
  'state': 'CO',
  'zip': '80216'},
 'UFL1': {'address': '15600 NW 15th Ave',
  'city': 'Miami Gardens',
  'code': 'UFL1',
  'notes': '37440',
  'state': 'FL',
  'zip': '33169'},
 'UFL2': {'address': '101 NE 23rd Street',
  'city': 'Miami',
  'code': 'UFL2',
  'notes': '',
  'state': 'FL',
  'zip': '33137'},
 'UFL3': {'address': '4430 East Adamo Suite 305',
  'city': 'Tampa',
  'code': 'UFL3',
  'notes': '30000',
  'state': 'FL',
  'zip': '33605'},
 'UFL4': {'address': '7469 Kingspointe Parkway',
  'city': 'Orlando',
  'code': 'UFL4',
  'notes': '96000',
  'state': 'FL',
  'zip': '32819'},
 'UGA1': {'address': '',
  'city': 'Atlanta',
  'code': 'UGA1',
  'notes': '',
  'state': 'GA',
  'zip': '30318'},
 'UGA2': {'address': '',
  'city': 'Atlanta',
  'code': 'UGA2',
  'notes': '',
  'state': 'GA',
  'zip': '30318'},
 'UGA3': {'address': '2160 Breckinridge Blvd Bldg 100 Suite 100',
  'city': 'Lawrenceville',
  'code': 'UGA3',
  'notes': '',
  'state': 'GA',
  'zip': '30043'},
 'UIL2': {'address': '1250 N Mittel Blvd',
  'city': 'Wood Dale',
  'code': 'UIL2',
  'notes': '',
  'state': 'IL',
  'zip': '60191'},
 'UMA3': {'address': '30 Northampton Street',
  'city': 'Boston',
  'code': 'UMA3',
  'notes': '',
  'state': 'MA',
  'zip': '2118'},
 'UMN1': {'address': '763 Kasota Ave.',
  'city': 'Minneapolis',
  'code': 'UMN1',
  'notes': '35000',
  'state': 'MN',
  'zip': '55414'},
 'UNC1': {'address': '',
  'city': 'Charlotte',
  'code': 'UNC1',
  'notes': '',
  'state': 'NC',
  'zip': '28201'},
 'UNC2': {'address': '3200 Bush Street',
  'city': 'Raleigh',
  'code': 'UNC2',
  'notes': '30000',
  'state': 'NC',
  'zip': '27609'},
 'UNJ1': {'address': '940 Monroe Street',
  'city': 'Hoboken',
  'code': 'UNJ1',
  'notes': '',
  'state': 'NJ',
  'zip': '7030'},
 'UNV1': {'address': '3650 East Post Road. Suite E',
  'city': 'Las Vegas',
  'code': 'UNV1',
  'notes': '',
  'state': 'NV',
  'zip': '89120'},
 'UOH1': {'address': 'Winton Hills',
  'city': 'Cincinnati',
  'code': 'UOH1',
  'notes': '',
  'state': 'OH',
  'zip': '45232'},
 'UOH2': {'address': '3563 Interchange Rd',
  'city': 'Columbus',
  'code': 'UOH2',
  'notes': '45700',
  'state': 'OH',
  'zip': '43204'},
 'UOR1': {'address': '2250 Northwest 22nd Avenue',
  'city': 'Portland',
  'code': 'UOR1',
  'notes': '',
  'state': 'OR',
  'zip': '97210'},
 'UTX1': {'address': '',
  'city': 'Irving',
  'code': 'UTX1',
  'notes': '',
  'state': 'TX',
  'zip': '75014'},
 'UTX2': {'address': '',
  'city': 'Austin',
  'code': 'UTX2',
  'notes': '',
  'state': 'TX',
  'zip': '73301'},
 'UTX3': {'address': '',
  'city': 'Houston',
  'code': 'UTX3',
  'notes': '',
  'state': 'TX',
  'zip': '77001'},
 'UTX4': {'address': 'PO Box 80387',
  'city': 'Seattle',
  'code': 'UTX4',
  'notes': '',
  'state': 'WA',
  'zip': '98108'},
 'UTX7': {'address': '4601 Gold Spike Drive',
  'city': 'Fort Worth',
  'code': 'UTX7',
  'notes': '',
  'state': 'TX',
  'zip': '76106'},
 'UTX8': {'address': '2800 S Texas Avenue Suite 401',
  'city': 'Bryan',
  'code': 'UTX8',
  'notes': '',
  'state': 'TX',
  'zip': '77802'},
 'UVA1': {'address': '5617 Industrial Dr. Suite A',
  'city': 'Springfield',
  'code': 'UVA1',
  'notes': '126900',
  'state': 'VA',
  'zip': '22151'},
 'UVA2': {'address': '',
  'city': 'Chesapeake',
  'code': 'UVA2',
  'notes': '',
  'state': 'VA',
  'zip': ''},
 'UVA3': {'address': '2034 Dabney Road',
  'city': 'Richmond',
  'code': 'UVA3',
  'notes': '11900',
  'state': 'VA',
  'zip': '23230'},
 'UWA1': {'address': '11710 118th Ave. N.E., Building B',
  'city': 'Kirkland',
  'code': 'UWA1',
  'notes': '38300',
  'state': 'WA',
  'zip': '98034'},
 'UWA2': {'address': '13537 Aurora Ave. N.',
  'city': 'North Seattle',
  'code': 'UWA2',
  'notes': '38400',
  'state': 'WA',
  'zip': '98133'},
 'UWA3': {'address': '2121 8th Ave.',
  'city': 'Seattle',
  'code': 'UWA3',
  'notes': '18900',
  'state': 'WA',
  'zip': '98121'},
 'UWA4': {'address': '76 S Lander Street',
  'city': 'Seattle',
  'code': 'UWA4',
  'notes': '',
  'state': 'WA',
  'zip': '98134'},
 'UWI1': {'address': '4111 W Mitchell Street',
  'city': 'Milwaukee',
  'code': 'UWI1',
  'notes': '',
  'state': 'WI',
  'zip': '53215'},
 'VAVP': {'address': '250 Enterprise Way',
  'city': 'Pittston',
  'code': 'VAVP',
  'notes': '',
  'state': 'PA',
  'zip': '18640'},
 'VUAT': {'address': '6855 Shannon Pkwy',
  'city': 'Union City',
  'code': 'VUAT',
  'notes': '744000',
  'state': 'GA',
  'zip': '30291'},
 'VUAV': {'address': '1 Commerce Road',
  'city': 'Pittston',
  'code': 'VUAV',
  'notes': '',
  'state': 'PA',
  'zip': '18640'},
 'VUBA': {'address': '1000 Keystone Industrial Park',
  'city': 'Scranton',
  'code': 'VUBA',
  'notes': '',
  'state': 'PA',
  'zip': '18512'},
 'VUBD': {'address': '17182 Nevada Avenue',
  'city': 'Victorville',
  'code': 'VUBD',
  'notes': '',
  'state': 'CA',
  'zip': '92345'},
 'VUGA': {'address': '508 Delaware Ave West',
  'city': 'Pittston',
  'code': 'VUGA',
  'notes': '',
  'state': 'PA',
  'zip': '18643'},
 'VUGE': {'address': '3450 DULLES DR',
  'city': 'Mira Loma',
  'code': 'VUGE',
  'notes': '',
  'state': 'CA',
  'zip': '91752'},
 'VUGP': {'address': '234 Walnut Bottom Road',
  'city': 'Shippensburg',
  'code': 'VUGP',
  'notes': '',
  'state': 'PA',
  'zip': '17257'},
 'VUHA': {'address': '700 Chase Street',
  'city': 'Gary',
  'code': 'VUHA',
  'notes': '',
  'state': 'IN',
  'zip': '46404'},
 'VUKF': {'address': '18120 Bishop Ave',
  'city': 'Carson',
  'code': 'VUKF',
  'notes': '',
  'state': 'CA',
  'zip': '90746'},
 'VUKG': {'address': '3201 Centre Parkway',
  'city': 'East Point',
  'code': 'VUKG',
  'notes': '',
  'state': 'GA',
  'zip': '30344'},
 'VUKH': {'address': '1901 W Airfield Dr',
  'city': 'DFW Airport',
  'code': 'VUKH',
  'notes': '',
  'state': 'TX',
  'zip': '75261'},
 'VUMC': {'address': '650 Commerce Pkwy W Drive',
  'city': 'Greenwood',
  'code': 'VUMC',
  'notes': '',
  'state': 'IN',
  'zip': '46143'},
 'VUMX': {'address': '241 E Pacific Coast Hwy',
  'city': 'Wilmington',
  'code': 'VUMX',
  'notes': '',
  'state': 'CA',
  'zip': '90744'},
 'VUOJ': {'address': '250 Declaration Avenue, Suite 500',
  'city': 'McDonough',
  'code': 'VUOJ',
  'notes': '',
  'state': 'GA',
  'zip': '30253'},
 'VUOK': {'address': '21837 W. Mississippi Ave',
  'city': 'Elwood',
  'code': 'VUOK',
  'notes': '',
  'state': 'IL',
  'zip': '60421'},
 'VUPJ': {'address': '101 Mars Road',
  'city': 'Wilmer',
  'code': 'VUPJ',
  'notes': '',
  'state': 'TX',
  'zip': '75172'},
 'VUPK': {'address': '6720 Oakley Industrial Blvd',
  'city': 'Union City',
  'code': 'VUPK',
  'notes': '',
  'state': 'GA',
  'zip': '30291'},
 'VUPM': {'address': '22001 84th Avenue',
  'city': 'Kent',
  'code': 'VUPM',
  'notes': '',
  'state': 'WA',
  'zip': '98032'},
 'VUPN': {'address': '340 Westridge Parkway',
  'city': 'McDonough',
  'code': 'VUPN',
  'notes': '',
  'state': 'GA',
  'zip': '30253'},
 'VUPO': {'address': '4808 Mountain Creek Parkway',
  'city': 'Dallas',
  'code': 'VUPO',
  'notes': '',
  'state': 'TX',
  'zip': '75236'},
 'VUPQ': {'address': '9211 Kaiser Way',
  'city': 'Fontana',
  'code': 'VUPQ',
  'notes': '',
  'state': 'CA',
  'zip': '92335'},
 'VUTD': {'address': '8291 Milliken Avenue',
  'city': 'Rancho Cucomonga',
  'code': 'VUTD',
  'notes': '',
  'state': 'CA',
  'zip': '91730'},
 'XUSB': {'address': '14900 Frye Rd',
  'city': 'Fort Worth',
  'code': 'XUSB',
  'notes': '495000',
  'state': 'TX',
  'zip': '76155'},
 'XUSC': {'address': '40 Logistics Dr',
  'city': 'Carlisle',
  'code': 'XUSC',
  'notes': '421200',
  'state': 'PA',
  'zip': '17013'},
 'XUSD': {'address': '1909 Zephyr St',
  'city': 'Stockton',
  'code': 'XUSD',
  'notes': '508000',
  'state': 'CA',
  'zip': '95206'},
 'XUSE': {'address': '5460 Industial Court Suite 300',
  'city': 'Whitestown',
  'code': 'XUSE',
  'notes': '624000',
  'state': 'IN',
  'zip': '46075'},
 'XUSF': {'address': '901 West Landstreet Road Suite C',
  'city': 'Orlando',
  'code': 'XUSF',
  'notes': '',
  'state': 'FL',
  'zip': '32824'},
 'XUSG': {'address': '9645 West Hills Court',
  'city': 'Kutztown',
  'code': 'XUSG',
  'notes': '',
  'state': 'PA',
  'zip': '19530'},
 'XUSH': {'address': '7037 West Van Buren Street',
  'city': 'Pheonix',
  'code': 'XUSH',
  'notes': '',
  'state': 'AZ',
  'zip': '85043'},
 'XUSJ': {'address': '1590 Tamarind Ave',
  'city': 'Rialto',
  'code': 'XUSJ',
  'notes': '',
  'state': 'CA',
  'zip': '92376'},
 'XUSK': {'address': '31450 W 196th St.',
  'city': 'Edgerton',
  'code': 'XUSK',
  'notes': '',
  'state': 'KS',
  'zip': '66021'},
 'XUSL': {'address': '610 Chelsea Rd',
  'city': 'Aberdeen',
  'code': 'XUSL',
  'notes': '',
  'state': 'MD',
  'zip': '21001'},
 'XUSM': {'address': '610 Chelsea Rd',
  'city': 'Aberdeen',
  'code': 'XUSM',
  'notes': '',
  'state': 'MD',
  'zip': '21001'},
 'XUSP': {'address': '1100 Woodley Road',
  'city': 'Aberdeen',
  'code': 'XUSP',
  'notes': '',
  'state': 'MD',
  'zip': '21001'},
 'XUSV': {'address': '2125 San Bernardino Ave',
  'city': 'San Bernardino',
  'code': 'XUSV',
  'notes': '',
  'state': 'CA',
  'zip': '92408'}}
